info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: GetUser.
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: GetUser.
      tags:
      - user
swagger: "2.0"
